title: Prashant's Experiment with Github Page
author: Prashant Singh
email: psonlinux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here I am trying know a Github feature which helps me to put the information
  related to the repository on a website hosted on Github :)

# social links
twitter_username: your-twitter-handle
github_username:  eelectron

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
